// List of all departments in the virtual office
export const departments = [
  "CF PS",
  "HR",
  "MFG & Purchases",
  "CF PS MFG EGYPT",
  "F&A",
  "FPWH",
  "General Operations",
  "GMDSO",
  "HS&E",
  "IWS",
  "Line-1",
  "Line-2",
  "Line-9",
  "Line-10",
  "P&E",
  "CFS ENG",
  "P&E Cairo/Karachi",
  "PFSS",
  "QA",
  "Regional GMDSO",
  "Regional Tech Pack",
  "RPM",
  "WH",
  "Shave Care Operations",
  "Shave Care Quality",
  "Storeroom",
  "TSG Matrix",
  "TSM",
  "Utilities",
]
